name: post-slack-message
on:
  pull_request_target:
    types:
      - labeled
jobs:
  post-slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: Post a slack message when PR contains security changes
        uses: slackapi/slack-github-action@v2.1.1
        if: github.event.label.name == 'security'
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "C026ZFU7H4K"
            text: "Pull Request with security changes: ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
